name: Building and testing RitehMaps 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_run:
    name: Build project & run tests
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: client/
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Yarn dependencies
      run: yarn install

    - name: Build project 
      run: yarn run build

    - name: Run tests
      run: yarn test